// import moment from 'moment'

// console.log(moment('12-12-2012').toDate())

export interface IUserData {
  id: number
  email: string
  name: string
  avatarImg: string
  createdAt?: Date
  token: string
}

export const userData: IUserData = {
  id: 1,
  email: 'yoptaEmail@yopta.com',
  name: 'Billi Harington',
  avatarImg:
    'https://www.google.com/url?sa=i&url=https%3A%2F%2Fsoundcloud.com%2Fuser-405654523&psig=AOvVaw2yi7SBVldonmYZww0eqaR6&ust=1699731024235000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCLDvm9GVuoIDFQAAAAAdAAAAABAE',
  // createdAt: moment().format('MMMM Do YYYY, h:mm:ss a'),
  token: '98sd32-fdfd3-dfs-123xcxs-32423',
}

export interface IRowData {
  id: number
  name: string
  band: string
  album: string
  year: string
  genre: string
  format: string
  image?: string
  description?: string
  urlVideo?: string
  rating?: number
}
export const rowsData: IRowData[] = [
  {
    id: 0,
    name: 'Nightcall',
    band: 'Kavinsky',
    album: 'OutRun',
    year: '2013',
    genre: 'Retrowave',
    format: 'flac',
    image: '/',
    description: 'something text',
    urlVideo: '/',
  },
  {
    id: 1,
    name: 'Bohemian Rhapsody',
    band: 'Queen',
    album: 'A Night at the Opera',
    year: '1975',
    genre: 'Rock',
    format: 'mp3',

    image: '/',
    description: 'something text',
    urlVideo: '/',
  },
  {
    id: 2,
    name: 'Hotel California',
    band: 'Eagles',
    album: 'Hotel California',
    year: '1976',
    genre: 'Rock',
    format: 'wav',

    image: '/',
    description: 'something text',
    urlVideo: '/',
  },
  {
    id: 3,
    name: 'Purple Haze',
    band: 'Jimi Hendrix',
    album: 'Are You Experienced',
    year: '1967',
    genre: 'Rock',
    format: 'flac',
    image: '/',
    description: 'something text',
    urlVideo: '/',
  },

  {
    id: 4,
    name: 'Imagine',
    band: 'John Lennon',
    album: 'Imagine',
    year: '1971',
    genre: 'Rock',
    format: 'mp3',
    image: '/',
    description: 'A classic song by John Lennon.',
    urlVideo: '/',
    rating: 4.9,
  },
  {
    id: 5,
    name: 'Thriller',
    band: 'Michael Jackson',
    album: 'Thriller',
    year: '1982',
    genre: 'Pop',
    format: 'mp3',
    image: '/',
    description: 'The iconic title track from the Thriller album.',
    urlVideo: '/',
    rating: 4.7,
  },
  {
    id: 6,
    name: 'Stairway to Heaven',
    band: 'Led Zeppelin',
    album: 'Led Zeppelin IV',
    year: '1971',
    genre: 'Rock',
    format: 'flac',
    image: '/',
    description: 'One of the greatest rock songs ever recorded.',
    urlVideo: '/',
    rating: 4.9,
  },
  {
    id: 7,
    name: 'Billie Jean',
    band: 'Michael Jackson',
    album: 'Thriller',
    year: '1982',
    genre: 'Pop',
    format: 'mp3',
    image: '/',
    description: "One of Michael Jackson's biggest hits.",
    urlVideo: '/',
    rating: 4.6,
  },
  {
    id: 8,
    name: 'Bohemian Rhapsody',
    band: 'Queen',
    album: 'A Night at the Opera',
    year: '1975',
    genre: 'Rock',
    format: 'mp3',
    image: '/',
    description: 'A rock classic by Queen.',
    urlVideo: '/',
    rating: 4.9,
  },
  {
    id: 9,
    name: 'Purple Rain',
    band: 'Prince',
    album: 'Purple Rain',
    year: '1984',
    genre: 'Pop',
    format: 'flac',
    image: '/',
    description: "An iconic song from Prince's Purple Rain album.",
    urlVideo: '/',
    rating: 4.8,
  },
  {
    id: 10,
    name: 'Hotel California',
    band: 'Eagles',
    album: 'Hotel California',
    year: '1976',
    genre: 'Rock',
    format: 'wav',
    image: '/',
    description: 'A classic rock song by the Eagles.',
    urlVideo: '/',
    rating: 4.7,
  },
  {
    id: 11,
    name: 'Smells Like Teen Spirit',
    band: 'Nirvana',
    album: 'Nevermind',
    year: '1991',
    genre: 'Grunge',
    format: 'mp3',
    image: '/',
    description: 'An iconic grunge anthem by Nirvana.',
    urlVideo: '/',
    rating: 4.9,
  },
  {
    id: 12,
    name: 'Boogie Wonderland',
    band: 'Earth, Wind & Fire',
    album: 'I Am',
    year: '1979',
    genre: 'Disco',
    format: 'mp3',
    image: '/',
    description: 'A disco classic by Earth, Wind & Fire.',
    urlVideo: '/',
    rating: 4.7,
  },
  {
    id: 13,
    name: "Sweet Child o' Mine",
    band: "Guns N' Roses",
    album: 'Appetite for Destruction',
    year: '1987',
    genre: 'Rock',
    format: 'flac',
    image: '/',
    description: "A rock ballad by Guns N' Roses.",
    urlVideo: '/',
    rating: 4.8,
  },
  {
    id: 14,
    name: 'Smooth',
    band: 'Santana featuring Rob Thomas',
    album: 'Supernatural',
    year: '1999',
    genre: 'Latin Rock',
    format: 'mp3',
    image: '/',
    description: 'A collaboration between Santana and Rob Thomas.',
    urlVideo: '/',
    rating: 4.6,
  },
  {
    id: 15,
    name: 'Wonderwall',
    band: 'Oasis',
    album: "(What's the Story) Morning Glory?",
    year: '1995',
    genre: 'Rock',
    format: 'mp3',
    image: '/',
    description: 'An iconic song by the British band Oasis.',
    urlVideo: '/',
    rating: 4.7,
  },
  {
    id: 16,
    name: 'Like a Rolling Stone',
    band: 'Bob Dylan',
    album: 'Highway 61 Revisited',
    year: '1965',
    genre: 'Folk Rock',
    format: 'flac',
    image: '/',
    description: 'A classic folk rock song by Bob Dylan.',
    urlVideo: '/',
    rating: 4.8,
  },
  {
    id: 17,
    name: 'Shape of You',
    band: 'Ed Sheeran',
    album: '÷ (Divide)',
    year: '2017',
    genre: 'Pop',
    format: 'mp3',
    image: '/',
    description: 'A popular pop song by Ed Sheeran.',
    urlVideo: '/',
    rating: 4.6,
  },
  {
    id: 18,
    name: "Livin' on a Prayer",
    band: 'Bon Jovi',
    album: 'Slippery When Wet',
    year: '1986',
    genre: 'Rock',
    format: 'mp3',
    image: '/',
    description: 'A classic rock anthem by Bon Jovi.',
    urlVideo: '/',
    rating: 4.7,
  },
  {
    id: 19,
    name: 'Let It Be',
    band: 'The Beatles',
    album: 'Let It Be',
    year: '1970',
    genre: 'Rock',
    format: 'flac',
    image: '/',
    description: 'An iconic song by The Beatles.',
    urlVideo: '/',
    rating: 4.8,
  },
  {
    id: 20,
    name: 'Smooth Operator',
    band: 'Sade',
    album: 'Diamond Life',
    year: '1984',
    genre: 'R&B',
    format: 'mp3',
    image: '/',
    description: 'A smooth R&B hit by Sade.',
    urlVideo: '/',
    rating: 4.6,
  },
  {
    id: 21,
    name: 'Wonderful Tonight',
    band: 'Eric Clapton',
    album: 'Slowhand',
    year: '1977',
    genre: 'Rock',
    format: 'mp3',
    image: '/',
    description: 'A classic rock ballad by Eric Clapton.',
    urlVideo: '/',
    rating: 4.7,
  },
]
